name: CI Python

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        packageDirectory: ["raiwidgets", "wrapped-flask"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ packageDirectory }}/requirements-dev.txt
          pip install ${{ packageDirectory }}/

      - name: flake8
        run: flake8

      - name: Run tests
        run: |
          pytest ${{ packageDirectory }}/tests/
